# Generated by Django 3.1.6 on 2021-03-02 13:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clonepages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgs', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
